### ISSUE TITLE
Add ip address to Customer Grid

### ISSUE THREAD

**Issue by WouterStulp** [Vinai/customer-registration-ip#2]
Hello,

ive added this extention to my store, it works perfect, but now i want to add the IP address of the customer to my Customer grid in the backend.

do you know if this is possible.

Thanks.

**Comment by Vinai** [comment]
I'm happy you find the modul useful.
Adding the IP to the customer grid is possible, but requires development efforts.
The IP address is stored in a customer attribute with the code `registration_remote_ip`.

I no longer do Magento 1 development (I haven't got a development environment set up any more), so I can't do it for you. You'll need to do it yourself or find someone.

**Comment by WouterStulp** [comment]
Thanks, ive figured it out with a colleage of mine.

I added this code to the grid.

`$this->addColumn('registration_remote_ip', array(
            'header' => 'Registration IP Address',
            'width'     => '100',
            'index' => 'registration_remote_ip'
        ));`

And added this to the protected function _prepareCollection()

`->addAttributeToSelect('registration_remote_ip')`

And i got the ip address of the customer.
